notifications:
  email: false

git:
  depth: false
  quiet: true

language: java
jdk: oraclejdk8
node_js: lts/*

addons:
  apt:
    packages:
      - bash
      - curl
      - tree
      - jq
      - python-pip
#      - docker-ce
#service:
#  - docker
env:
  global:
    - TERM=dumb
    - SENTINEL_PORT=8888
#    - ZOOKEEPER_PORT=2181
#    - ZOOKEEPER_PEERS=localhost:${ZOOKEEPER_PORT}
#    - KAFKA_HOME=/tmp/kafka
#    - KAFKA_PORT=9092
#    - KAFKA_PEERS=localhost:${KAFKA_PORT}

install: true
before_install:
#  - sudo pip install docker-compose httpie >/dev/null 2>&1
#  #
#  - wget https://www.apache.org/dist/kafka/2.1.0/kafka_2.12-2.1.0.tgz -O ${KAFKA_HOME}.tgz
#  - mkdir -p ${KAFKA_HOME} && tar xzf ${KAFKA_HOME}.tgz -C ${KAFKA_HOME} --strip-components 1
#  - bash -c "${KAFKA_HOME}/bin/zookeeper-server-start.sh ${KAFKA_HOME}/config/zookeeper.properties &"
#  - wait_for ${ZOOKEEPER_PORT}
#  - bash -c "${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/server.properties &"
#  - wait_for ${KAFKA_PORT}
#  - bash -c "${KAFKA_HOME}/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic bank-account-domain-events-kafka-template-topic.1 --zookeeper ${ZOOKEEPER_PEERS}"
  - sudo apt-get update -yqq
  - sudo pip install httpie >/dev/null 2>&1
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8000 8080

script:
  - ./mvnw -U
  - (./mvnw -pl :sentinel-dashboard &) || true
  - wait_for ${SENTINEL_PORT}
  #
  - SERVER_PORT=8001 java -jar ./01-default-flow-limiting/target/*.jar &
  - wait_for 8001
  - http :8001/hello
  - http :8001/hello
  - http :8001/hello || true
    - sleep 1
  - stop_any 8001
  #
  - SERVER_PORT=8002 java -jar ./02-fallback-block-page/target/*.jar &
  - wait_for 8002
  - http :8002/hello
  - http :8002/hello
  - http :8002/hello || true
    - sleep 1
  - stop_any 8002
  #
  - SERVER_PORT=8003 java -jar ./03-url-block-handler/target/*.jar &
  - wait_for 8003
  - http :8003/hello
  - http :8003/hello
  - http :8003/hello || true
  - sleep 1
  - stop_any 8003

after_script:
  - stop_any ${SENTINEL_PORT}

cache:
  pip: true
  packages: true
  directories:
    - ${HOME}/.m2
